### ISSUE TITLE
Sometimes people (or at least one person) can't login, and we don't do a great job of surfacing that

### ISSUE THREAD

**Issue by bakert** [silasary/Penny-Dreadful-Discord-Bot#11625]
stefangoerke encountered this (on the Brave browser, works ok on Chrome):

```
[2023-08-22 21:09:54,807] ERROR in app: Exception on /authenticate/callback/ [GET]
Traceback (most recent call last):
  File "/home/pdadmin/decksite/.venv/lib/python3.10/site-packages/flask/app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/pdadmin/decksite/.venv/lib/python3.10/site-packages/flask/app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/pdadmin/decksite/.venv/lib/python3.10/site-packages/flask_restx/api.py", line 674, in error_router
    return original_handler(e)
  File "/home/pdadmin/decksite/.venv/lib/python3.10/site-packages/flask/app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/pdadmin/decksite/.venv/lib/python3.10/site-packages/flask/app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/pdadmin/decksite/./shared_web/flask_app.py", line 109, in authenticate_callback
    oauth.setup_session(request.url)
  File "/home/pdadmin/decksite/./shared_web/oauth.py", line 23, in setup_session
    token = discord.fetch_token(
  File "/home/pdadmin/decksite/.venv/lib/python3.10/site-packages/requests_oauthlib/oauth2_session.py", line 244, in fetch_token
    self._client.parse_request_uri_response(
  File "/home/pdadmin/decksite/.venv/lib/python3.10/site-packages/oauthlib/oauth2/rfc6749/clients/web_application.py", line 220, in parse_request_uri_response
    response = parse_authorization_code_response(uri, state=state)
  File "/home/pdadmin/decksite/.venv/lib/python3.10/site-packages/oauthlib/oauth2/rfc6749/parameters.py", line 278, in parse_authorization_code_response
    raise MismatchingStateError()
oauthlib.oauth2.rfc6749.errors.MismatchingStateError: (mismatching_state) CSRF Warning! State not equal in request and response.
[2023-08-22 21:09:54,809] ERROR in logger: At request path: /authenticate/callback/
werkzeug.exceptions.InternalServerError: 500 Internal Server Error: The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.
Last login: Tue Aug 22 10:00:38 on ttys000
s%                                                                              [dent ~] ssh hb
Welcome to Ubuntu 18.04.6 LTS (GNU/Linux 6.2.9-x86_64-linode160 x86_64)

 * Documentation:  https://help.ubuntu.com
 * Management:     https://landscape.canonical.com
 * Support:        https://ubuntu.com/advantage
You have new mail.
Last login: Mon Aug 21 00:16:57 2023 from 136.25.106.188
[bakert@hotblackdesiato ~]$ logout
Connection to hotblackdesiato.bluebones.net closed.
[dent ~] ssh decksite
Welcome to Ubuntu 22.04.2 LTS (GNU/Linux 5.15.0-67-generic x86_64)

 * Documentation:  https://help.ubuntu.com
 * Management:     https://landscape.canonical.com
 * Support:        https://ubuntu.com/advantage

  System information as of Tue Aug 22 09:12:42 PM UTC 2023

  System load:  0.28759765625    Temperature:           54.0 C
  Usage of /:   1.3% of 3.58TB   Processes:             263
  Memory usage: 33%              Users logged in:       1
  Swap usage:   0%               IPv4 address for eth0: 50.21.182.26

 * Strictly confined Kubernetes makes edge and IoT secure. Learn how MicroK8s
   just raised the bar for easy, resilient and secure K8s cluster deployment.

   https://ubuntu.com/engage/secure-kubernetes-at-the-edge

Expanded Security Maintenance for Applications is not enabled.

76 updates can be applied immediately.
1 of these updates is a standard security update.
To see these additional updates run: apt list --upgradable

2 additional security updates can be applied with ESM Apps.
Learn more about enabling ESM Apps service at https://ubuntu.com/esm


*** System restart required ***
Last login: Mon Aug 21 01:21:09 2023 from 136.25.106.188
Linux D931289 5.15.0-67-generic x86_64
 21:12:42 up 158 days, 15:44,  3 users,  load average: 0.29, 0.34, 0.36
 pdadmin@D931289  ~  mysql -A -u pennydreadful -pebKDmTuFFpGxaYV3pjUZdWUB decksite

Welcome to the MariaDB monitor.  Commands end with ; or \g.
Your MariaDB connection id is 620585
Server version: 10.6.12-MariaDB-0ubuntu0.22.04.1-log Ubuntu 22.04

Copyright (c) 2000, 2018, Oracle, MariaDB Corporation Ab and others.

Type 'help;' or '\h' for help. Type '\c' to clear the current input statement.

MariaDB [decksite]> ^DBye
 pdadmin@D931289  ~  sudo grep ERROR /var/log/uwsgi/app/decksite.log^C
 pdadmin@D931289  ~  sudo tail -f /var/log/uwsgi/app/decksite.log
[sudo] password for pdadmin: 
```

</details>

[2023-08-22 21:09:55,632] ERROR in logger: Github error
500 Internal Server Error: The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.
[pid: 3459194|app: 0|req: 4150/497301] 162.158.111.5 () {76 vars in 2480 bytes} [Tue Aug 22 21:09:54 2023] GET /authenticate/callback/?code=MENh0qoj66VirAH99HyAJKmWPIYau1&state=EkNdoC2RedsggDozPfOfRlwXpqxlaE => generated 23289 bytes in 1257 msecs (HTTP/1.1 500) 6 headers in 787 bytes (1 switches on core 1)
[2023-08-22 21:11:56,642] WARNING in logger: 404 Not Found /www.tar.gz
[pid: 3459194|app: 0|req: 4539/497762] 162.158.103.150 () {56 vars in 948 bytes} [Tue Aug 22 21:11:56 2023] GET /www.tar.gz => generated 25388 bytes in 36 msecs (HTTP/1.1 404) 4 headers in 132 bytes (1 switches on core 1)
 !  pdadmin@D931289  ~  sudo less  /var/log/uwsgi/app/decksite.log                                                                                                                                                                   11.3s  Tue 22 Aug 2023 09:13:06 PM UTC

Exception_hash: 4f3017cc1a3a995ff66263c116a23bf02f85217c
<details><summary><strong>Request Data</strong></summary>

```

Request Method: GET
Path: /authenticate/callback/?code=MENh0qoj66VirAH99HyAJKmWPIYau1&state=EkNdoC2RedsggDozPfOfRlwXpqxlaE
Cookies: ImmutableMultiDict([('hide_intro', 'True'), ('session', '.eJxlkNtuwjAQRP9lnyMS7pg3aAsIqRcqFUqrKnLiTWLwJbIdWor49xokQiUeZ3Y94z0HiEs0kipUDobOVBgAZZIrGKpKiAAYSi41qyW3qTYs5jeO0CkVeHGvc67ivOLC64wK6-OFznNkp1qr1b8g6XIdVxaNorLO0bRyRSu2jjrvwXQyesuTebR46fSXrZTZQZMnq-YG5_dPTkO97_QW_QkHoGmK1l40tCf6I6pwhtvNqDu5e5W752L2M18_9ne_OPbv8afkBm1MPY1mj0Qk6pNm1CDtbrfXJ9f5CVAv6gyiKACDmbeKumSVid3ELUibi-8iec_X9qEzXS5IbzpVhPgSD6z013x6Sh47z_beOzOy8BXAOSZ2-9MKjJEaNHAM4IaXoyZH_00onCvtMAxLVGrPDFKWVULSnKeNVMuQJrpyIRz_AIREp50.ZL_7WA.g0_AvwE3GK8pkasiGSQvcqT5XVs'), ('session', '.eJxlkFtPAjEQhf_LPG9gEVgsb4JcYqIIDwoas6nb2W6ll7Xtcg3_3UICmPB4zkzP6Xx7SEu0imrUHrreVhgBZUpo6OpKyggYKqEMu0jhMmNZKm4caTIq8exe50KnvBIy6JxKF-Kl4RzZsdYZ_S9IeW7SyqHVVF1yDK18cZc6T33wYLB8YaZ_N0PmOH80u9d8ks_kel7-biQdwGXfmyWGE_ZAswydO2toDs1HXOEYlz8P7WF_plaTYrx5Wjx3Vjvshfe4KYVFl9JAo5GQmMQd0ohrpNluJx1ynR8BJXHrPo4jsJgHq7iUvOdyNfRT0hRyXXzP-cINWqO3KUlGI01IKAnAynDNZ6AUsIt8G7wTIwdfEZxiUr89rkAPqUULhwhueHlqOYZvQuF96br1eolab5lFyvJKKspFVsuMqsPhD5MMpwc.ZOUkHg.0zYRCVnioxQ6ifUtzJloVw_d5ic'), ('views', '19')])
Endpoint: authenticate_callback
View Args: {}
Person: None
Referrer: https://discord.com/
Request Data: {}
Host: pennydreadfulmagic.com
Connection: Keep-Alive
Accept-Encoding: gzip
X-Forwarded-For: 2a02:810d:8b80:1f18:9809:a41b:d533:2e10
Cf-Ray: 7fae1976eafe18e9-FRA
X-Forwarded-Proto: https
Cf-Visitor: {"scheme":"https"}
Sec-Ch-Ua: "Chromium";v="116", "Not)A;Brand";v="24", "Brave";v="116"
Sec-Ch-Ua-Mobile: ?0
Sec-Ch-Ua-Platform: "Windows"
Upgrade-Insecure-Requests: 1
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/116.0.0.0 Safari/537.36
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8
Sec-Gpc: 1
Accept-Language: pt-BR,pt;q=0.7
Sec-Fetch-Site: cross-site
Sec-Fetch-Mode: navigate
Sec-Fetch-User: ?1
Sec-Fetch-Dest: document
Referer: https://discord.com/
Cookie: hide_intro=True; session=.eJxlkNtuwjAQRP9lnyMS7pg3aAsIqRcqFUqrKnLiTWLwJbIdWor49xokQiUeZ3Y94z0HiEs0kipUDobOVBgAZZIrGKpKiAAYSi41qyW3qTYs5jeO0CkVeHGvc67ivOLC64wK6-OFznNkp1qr1b8g6XIdVxaNorLO0bRyRSu2jjrvwXQyesuTebR46fSXrZTZQZMnq-YG5_dPTkO97_QW_QkHoGmK1l40tCf6I6pwhtvNqDu5e5W752L2M18_9ne_OPbv8afkBm1MPY1mj0Qk6pNm1CDtbrfXJ9f5CVAv6gyiKACDmbeKumSVid3ELUibi-8iec_X9qEzXS5IbzpVhPgSD6z013x6Sh47z_beOzOy8BXAOSZ2-9MKjJEaNHAM4IaXoyZH_00onCvtMAxLVGrPDFKWVULSnKeNVMuQJrpyIRz_AIREp50.ZL_7WA.g0_AvwE3GK8pkasiGSQvcqT5XVs; views=19; session=.eJxlkFtPAjEQhf_LPG9gEVgsb4JcYqIIDwoas6nb2W6ll7Xtcg3_3UICmPB4zkzP6Xx7SEu0imrUHrreVhgBZUpo6OpKyggYKqEMu0jhMmNZKm4caTIq8exe50KnvBIy6JxKF-Kl4RzZsdYZ_S9IeW7SyqHVVF1yDK18cZc6T33wYLB8YaZ_N0PmOH80u9d8ks_kel7-biQdwGXfmyWGE_ZAswydO2toDs1HXOEYlz8P7WF_plaTYrx5Wjx3Vjvshfe4KYVFl9JAo5GQmMQd0ohrpNluJx1ynR8BJXHrPo4jsJgHq7iUvOdyNfRT0hRyXXzP-cINWqO3KUlGI01IKAnAynDNZ6AUsIt8G7wTIwdfEZxiUr89rkAPqUULhwhueHlqOYZvQuF96br1eolab5lFyvJKKspFVsuMqsPhD5MMpwc.ZOUkHg.0zYRCVnioxQ6ifUtzJloVw_d5ic
Priority: u=0, i
Cdn-Loop: cloudflare
Cf-Connecting-Ip: 2a02:810d:8b80:1f18:9809:a41b:d533:2e10
Cf-Ipcountry: DE
```

</details>

[2023-08-22 21:09:55,632] ERROR in logger: Github error
500 Internal Server Error: The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.
[pid: 3459194|app: 0|req: 4150/497301] 162.158.111.5 () {76 vars in 2480 bytes} [Tue Aug 22 21:09:54 2023] GET /authenticate/callback/?code=MENh0qoj66VirAH99HyAJKmWPIYau1&state=EkNdoC2RedsggDozPfOfRlwXpqxlaE => generated 23289 bytes in 1257 msecs (HTTP/1.1 500) 6 headers in 787 bytes (1 switches on core 1)
```

**Comment by bakert** [comment]
We didn't get any notification of this so it could be happening a lot.

**Comment by bakert** [comment]
<img width="371" alt="image" src="https://github.com/PennyDreadfulMTG/Penny-Dreadful-Tools/assets/1541/cbd443e0-d35a-4677-87c8-a8e18b205eb2">
