### ISSUE TITLE
/bug command complains about bad credentials and does not log bug

### ISSUE THREAD

**Issue by bakert** [silasary/Penny-Dreadful-Discord-Bot#12025]
```Error: BadCredentialsException
Traceback (most recent call last):
  File "/penny/mtgbot/.venv/lib/python3.10/site-packages/interactions/client/client.py", line 1900, in __dispatch_interaction
    response = await callback
  File "/penny/mtgbot/.venv/lib/python3.10/site-packages/interactions/client/client.py", line 1771, in _run_slash_command
    return await command(ctx, **ctx.kwargs)
  File "/penny/mtgbot/.venv/lib/python3.10/site-packages/interactions/models/internal/command.py", line 132, in __call__
    await self.call_callback(self.callback, context)
  File "/penny/mtgbot/.venv/lib/python3.10/site-packages/interactions/models/internal/application_commands.py", line 833, in call_callback
    return await self.call_with_binding(callback, ctx, *new_args, **new_kwargs)
  File "/penny/mtgbot/.venv/lib/python3.10/site-packages/interactions/models/internal/callback.py", line 43, in call_with_binding
    return await callback(*args, **kwargs)
  File "/penny/mtgbot/discordbot/commands/bug.py", line 19, in bug
    issue = repo.create_issue(text, str(ctx.author))
  File "/penny/mtgbot/shared/repo.py", line 94, in create_issue
    git_repo = g.get_repo(repo_name)
  File "/penny/mtgbot/.venv/lib/python3.10/site-packages/github/MainClass.py", line 363, in get_repo
    headers, data = self.__requester.requestJsonAndCheck("GET", url)
  File "/penny/mtgbot/.venv/lib/python3.10/site-packages/github/Requester.py", line 442, in requestJsonAndCheck
    return self.__check(
  File "/penny/mtgbot/.venv/lib/python3.10/site-packages/github/Requester.py", line 487, in __check
    raise self.__createException(status, responseHeaders, data)
github.GithubException.BadCredentialsException: 401 {"message": "Bad credentials", "documentation_url": "https://docs.github.com/rest"}```

**Comment by bakert** [comment]
I fixed this.
